---
title: "Conflitos em times de desenvolvimento de software no contexto dos projetos de disciplinas de graduação"
subtitle: "Um estudo no Bacharelado em Ciência da Computação da Universidade Federal de Campina Grande"
bibliography: 'metadata/references.bib'
csl: 'metadata/associacao-brasileira-de-normas-tecnicas.csl'
fontsize: 11pt
author:
  - "Thiago Nascimento de Lima^[Autor correspondente. thiago.lima@ccc.ufcg.edu.br]"
  - "Gabriela Roberta Alverga do Nascimento"
  - "Ítallo de Sousa Silva"
  - "João Marcelo Fernandes da Silva Júnior"
classoption:
  - twocolumn
header-includes:
  - \usepackage{indentfirst}
  - \usepackage{floatrow}
  - \usepackage{lipsum}
  - \setlength\parindent{35pt}
  - \floatsetup[figure]{capposition=top}
  - \floatsetup[table]{capposition=top}
fig_caption: yes
indent: true
lang: "pt-BR"
link-citations: yes
output: 
  bookdown::pdf_document2:
    df_print: kable
    fig_caption: yes
    number_sections: false
    toc: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
options(scipen = 10, digits = 4, OutDec = ",")
```

```{r child = 'partes/00-resumo.Rmd'}
```

```{r child = 'partes/01-introducao.Rmd'}
```

```{r child = 'partes/02-revisao_literatura.Rmd'}
```

```{r child = 'partes/03-metodologia.Rmd'}
```

```{r child = 'partes/04-analise_exploratoria.Rmd'}
```

```{r child = 'partes/05-conclusao.Rmd'}
```

# Referências