# Conclusões e trabalhos futuros

Através do resultado obtido pelo estudo foi constatado que os conflitos mais frequentes em times de desenvolvimento decorrem do desacordo na perspectiva dos prazos, ou seja, determinar a duração e data de entrega das tarefas. Entretanto, os conflitos que mais impactaram no sucesso do projeto provém das decisões de gerenciamento, com as definições da hierarquia, responsabilidade e plano de execução. Com relação às abordagens de soluções aplicadas pelos times, os métodos mais aplicados foram os de abordagem colaborativa, tais como apaziguamento, confronto e negociação. Além disso, os modos de gerenciamento identificados como menos efetivos foram os que ignoram ou propõem soluções autoritárias para os conflitos, tais como evasão e imposição.
 
A compreensão sobre conflitos e modos de gerenciamento têm influência na gestão de conflitos, sendo assim, conhecer sobre a frequência e impacto dos tipos de conflito, possibilita ao gerente de time direcionar, estrategicamente, seu esforço na contenção de conflitos e mitigação de riscos. Além disso, este trabalho fornece suporte na escolha de uma técnica de resolução de conflito, ao apresentar informações da sua efetividade.

Possíveis trabalhos futuros podem realizar uma expansão do universo do discurso da pesquisa, dando enfoque em especial a três direcionamentos: 

- Expansão da amostra, no intuito de minimizar erros estatísticos e possíveis viés dos resultados.

- Investigação mais ampla das fontes de conflito, devido esta pesquisa ter tido um caráter estimulado, ao apresentar fontes de conflitos retiradas da literatura, outras fontes mais frequentes podem ter sido negligenciadas, assim realizar uma pesquisa espontânea deve contribuir positivamente para as conclusões. 

- Realização de trabalhos que pontuem as consequências da não resolução dos conflitos citados e quais os males, em potencial, que elas podem infligir ao projeto. Podendo, ainda, incluir uma análise de caso comparativa entre as técnicas de solução aplicadas.